CREATE TABLE GA(ORDER_ID STRING, ORDER_NUMBER STRING, ENTERPRISE_ID STRING, OUTLETS_NAME STRING, R_NAME STRING, R_JOB_NUMBER STRING, R_PHONE STRING, S_NAME STRING, S_JOB_NUMBER STRING, S_PHONE STRING, IS_RECV_PAY STRING, CAR_NUMBER STRING, DRIVER_NAME STRING, DRIVER_PHONE STRING, SENDER_NAME STRING, SENDER_CNUMBER STRING, SENDER_QH STRING, SENDER_PHONE STRING, SEND_ADDRESS STRING, SEND_ADDR_DETAIL STRING, SEND_YZ_CODE STRING, SEND_TIME STRING, RECV_NAME STRING, RECV_CNUMBER STRING, RECV_QH STRING, RECV_PHONE STRING, RECV_ADDRESS STRING, RECV_ADDR_DETAIL STRING, RECV_YZ_CODE STRING, RECV_TIME STRING, IS_NUM_NOTIFYSEND STRING, OBJECT_NAME STRING, IS_NUM_NOTIFYRECV STRING, OBJECT_WEIGHT STRING, OBJECT_VOLUME STRING, OBJECT_BJ_MONEY STRING, ORDER_TYPE STRING)

SELECT * FROM (SELECT *, FIRST_VALUE(SEND_ADDRESS) OVER (PARTITION BY SENDER_NAME) FIRST_SEND_ADDRESS FROM GA) AS GA1 WHERE SEND_ADDRESS != FIRST_SEND_ADDRESS;

发件人同姓名，发件地址不同
CREATE TABLE GA2 AS SELECT GA.* FROM (SELECT SENDER_NAME FROM GA GROUP BY SENDER_NAME HAVING SUM(DISTINCT SEND_ADDRESS) > 1) GA1 JOIN GA ON GA.SENDER_NAME = GA1.SENDER_NAME;

公司不同
SELECT GA.* FROM (SELECT SENDER_NAME FROM GA2 GROUP BY SENDER_NAME HAVING SUM(DISTINCT ENTERPRISE_ID) > 1) GA3 JOIN GA ON GA.SENDER_NAME = GA3.SENDER_NAME;
